### ISSUE TITLE
Serving static files with Suitelet

### ISSUE THREAD

**Issue by adamkostopoulos** [mayerlench/react-netsuite-boilerplate#1]
Very helpful repo! 

Any updates on how to share and consume additional folders / file types in the static folder within NetSuite?

I have a React app (pretty much just CRA + Bryntum Scheduler) that I have rendering within NetSuite but I'm missing web fonts .woffs and fontawesome that are stored in my static/media folder. The Suitelet gets a 404 when it tries to call them.

I tried editing the Suitelet code to include the static/media path but I'm not able to get them to load.

```
...
    const getHtml = (STATIC_FOLDER_NAME) => {
        try {
            const files = getStaticFiles(STATIC_FOLDER_NAME)
            const htmlId = files.find(f => f.name === 'index.html').id
            const html = file.load({ id: htmlId }).getContents()
                .replace(/\/static\/js\//g, '')
                .replace(/\/static\/css\//g, '')
                .replace(/\/static\/media\//g, '')
                .replace(/\/manifest/, 'manifest')
                .replace(/\/favicon/, 'favicon')
...
```

Any advice?

**Comment by mayerlench** [comment]
What is the path in the build folder to your fonts?

The `.replace` in the above code replace the static folder relative paths and the reduce lower down in the code adds the NetSuite URL to the media file.
