### ISSUE TITLE
Proxy issue

### ISSUE THREAD

**Issue by jcmujica** [mayerlench/react-netsuite-boilerplate#2]
Hello,

I have been trying to set this up using your instructions, however, the package.json proxy is not beign applied to the RESTlet requests.

I keep getting the following message: VM49:1 GET http://localhost:3000/app/site/hosting/restlet.nl?script=2350&deploy=1 403 (Forbidden).

As you can see requests are still being performed using the localhost base.

**Comment by mayerlench** [comment]
Hey while this should still work, I would check out the new version. https://www.npmjs.com/package/@finitydevs/create-spa-netsuite

**Comment by quantuminformation** [comment]
So you don't need backbone to work with netsuite?

**Comment by mayerlench** [comment]
> So you don't need backbone to work with netsuite?

I believe your are referring to SCA. This isn't for SCA. This is to create custom UIs in netsuite using react

Also I should mention this project has been updated with many new features and is alot easier to use.

It now has its own scaffolding CLI and here https://www.npmjs.com/package/@finitydevs/create-spa-netsuite
